"""add location; business

Revision ID: 1f0c9f59e737
Revises: 19bfe4945f58
Create Date: 2015-07-15 16:07:19.277246

"""

# revision identifiers, used by Alembic.
revision = '1f0c9f59e737'
down_revision = '19bfe4945f58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.String(length=40), nullable=False),
    sa.Column('location_street', sa.String(length=128), nullable=True),
    sa.Column('location_suite', sa.String(length=128), nullable=True),
    sa.Column('location_city', sa.String(length=64), nullable=True),
    sa.Column('location_state', sa.String(length=32), nullable=True),
    sa.Column('location_zip', sa.String(length=10), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index(op.f('ix_location_location_id'), 'location', ['location_id'], unique=False)
    op.create_table('business',
    sa.Column('bus_id', sa.String(length=40), nullable=False),
    sa.Column('bus_address', sa.String(length=40), nullable=False),
    sa.Column('bus_name', sa.String(length=99), nullable=False),
    sa.Column('bus_state', sa.Integer(), nullable=False),
    sa.Column('bus_website', sa.String(length=128), nullable=True),
    sa.Column('bus_phone', sa.String(length=20), nullable=True),
    sa.Column('bus_email', sa.String(length=64), nullable=True),
    sa.Column('bus_account', sa.String(length=40), nullable=True),
    sa.Column('bus_headline', sa.String(length=140), nullable=True),
    sa.Column('bus_description', sa.String(length=5000), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bus_account'], ['account.userid'], ),
    sa.ForeignKeyConstraint(['bus_address'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('bus_id')
    )
    op.create_index(op.f('ix_business_bus_id'), 'business', ['bus_id'], unique=False)
    op.add_column(u'referral', sa.Column('ref_business', sa.String(length=40), nullable=False))
    op.drop_index('ix_referral_ref_uuid', table_name='referral')
    op.create_index(op.f('ix_referral_ref_uuid'), 'referral', ['ref_uuid'], unique=False)
    op.drop_constraint(u'referral_ref_profile_fkey', 'referral', type_='foreignkey')
    op.create_foreign_key(None, 'referral', 'business', ['ref_business'], ['bus_id'])
    op.drop_column(u'referral', 'ref_profile')
    op.drop_index('ix_referral_list_list_uuid', table_name='referral_list')
    op.create_index(op.f('ix_referral_list_list_uuid'), 'referral_list', ['list_uuid'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_list_list_uuid'), table_name='referral_list')
    op.create_index('ix_referral_list_list_uuid', 'referral_list', ['list_uuid'], unique=True)
    op.add_column(u'referral', sa.Column('ref_profile', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referral', type_='foreignkey')
    op.create_foreign_key(u'referral_ref_profile_fkey', 'referral', 'profile', ['ref_profile'], ['prof_id'])
    op.drop_index(op.f('ix_referral_ref_uuid'), table_name='referral')
    op.create_index('ix_referral_ref_uuid', 'referral', ['ref_uuid'], unique=True)
    op.drop_column(u'referral', 'ref_business')
    op.drop_index(op.f('ix_business_bus_id'), table_name='business')
    op.drop_table('business')
    op.drop_index(op.f('ix_location_location_id'), table_name='location')
    op.drop_table('location')
    ### end Alembic commands ###
