"""update location: add business ptr; business makes location optional (for peeps)

Revision ID: 36d224664a51
Revises: 1f0c9f59e737
Create Date: 2015-07-16 12:46:55.675162

"""

# revision identifiers, used by Alembic.
revision = '36d224664a51'
down_revision = '1f0c9f59e737'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('businessreference')
    op.drop_constraint(u'business_bus_address_fkey', 'business', type_='foreignkey')
    op.drop_column('business', 'bus_address')
    op.add_column('location', sa.Column('business', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'location', 'business', ['business'], ['bus_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.drop_column('location', 'business')
    op.add_column('business', sa.Column('bus_address', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
    op.create_foreign_key(u'business_bus_address_fkey', 'business', 'location', ['bus_address'], ['location_id'])
    op.create_table('businessreference',
    sa.Column('br_uuid', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('br_bus_acct', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('br_bus_prof', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('br_req_mail', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('br_req_prof', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('br_flags', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['br_bus_acct'], [u'account.userid'], name=u'businessreference_br_bus_acct_fkey'),
    sa.ForeignKeyConstraint(['br_bus_prof'], [u'profile.prof_id'], name=u'businessreference_br_bus_prof_fkey'),
    sa.PrimaryKeyConstraint('br_uuid', name=u'businessreference_pkey')
    )
    ### end Alembic commands ###
