"""empty message

Revision ID: 3e0fc93feabe
Revises: 5c2e911074f
Create Date: 2015-07-02 15:21:32.225943

"""

# revision identifiers, used by Alembic.
revision = '3e0fc93feabe'
down_revision = '5c2e911074f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral', sa.Column('ref_flags', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'referral_list_member_map', ['id'])
    op.create_unique_constraint(None, 'referral_list_referral_map', ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referral_list_referral_map', type_='unique')
    op.drop_constraint(None, 'referral_list_member_map', type_='unique')
    op.drop_column('referral', 'ref_flags')
    op.drop_constraint(None, 'project', type_='foreignkey')
    ### end Alembic commands ###
