"""add profile to referral

Revision ID: 4fddf47bf550
Revises: 36d224664a51
Create Date: 2015-07-22 16:06:03.374108

"""

# revision identifiers, used by Alembic.
revision = '4fddf47bf550'
down_revision = '36d224664a51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - CAH adjusted! ###
    op.add_column('referral', sa.Column('ref_profile', sa.String(length=40), nullable=False))
    op.create_foreign_key(None, 'referral', 'profile', ['ref_profile'], ['prof_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referral', type_='foreignkey')
    op.drop_column('referral', 'ref_profile')
    ### end Alembic commands ###
