"""empty message

Revision ID: 5c2e911074f
Revises: 57f6ead1372e
Create Date: 2015-06-30 19:53:56.803268

"""

# revision identifiers, used by Alembic.
revision = '5c2e911074f'
down_revision = '57f6ead1372e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral',
    sa.Column('ref_uuid', sa.String(length=40), nullable=False),
    sa.Column('ref_profile', sa.String(length=40), nullable=False),
    sa.Column('ref_content', sa.String(length=200), nullable=False),
    sa.Column('ref_project', sa.String(length=128), nullable=True),
    sa.Column('ref_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ref_profile'], ['profile.prof_id'], ),
    sa.PrimaryKeyConstraint('ref_uuid')
    )
    op.create_index(op.f('ix_referral_ref_uuid'), 'referral', ['ref_uuid'], unique=True)
    op.create_table('referral_list',
    sa.Column('list_uuid', sa.String(length=40), nullable=False),
    sa.Column('list_profile', sa.String(length=40), nullable=False),
    sa.Column('list_project', sa.String(length=40), nullable=True),
    sa.Column('list_name', sa.String(length=40), nullable=True),
    sa.Column('list_desc', sa.String(length=120), nullable=True),
    sa.Column('list_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['list_profile'], ['profile.prof_id'], ),
    sa.ForeignKeyConstraint(['list_project'], ['project.proj_id'], ),
    sa.PrimaryKeyConstraint('list_uuid')
    )
    op.create_index(op.f('ix_referral_list_list_uuid'), 'referral_list', ['list_uuid'], unique=True)
    op.create_table('referral_list_member_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_reflist', sa.String(length=40), nullable=False),
    sa.Column('map_profile', sa.String(length=40), nullable=False),
    sa.Column('map_control', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['map_profile'], ['profile.prof_id'], ),
    sa.ForeignKeyConstraint(['map_reflist'], ['referral_list.list_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_referral_list_member_map_map_reflist'), 'referral_list_member_map', ['map_reflist'], unique=False)
    op.create_table('referral_list_referral_map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_reflist', sa.String(length=40), nullable=False),
    sa.Column('map_referal', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['map_referal'], ['referral.ref_uuid'], ),
    sa.ForeignKeyConstraint(['map_reflist'], ['referral_list.list_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_referral_list_referral_map_map_referal'), 'referral_list_referral_map', ['map_referal'], unique=False)
    op.create_index(op.f('ix_referral_list_referral_map_map_reflist'), 'referral_list_referral_map', ['map_reflist'], unique=False)
    op.create_index(op.f('ix_project_proj_id'), 'project', ['proj_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_index(op.f('ix_project_proj_id'), table_name='project')
    op.drop_index(op.f('ix_referral_list_referral_map_map_reflist'), table_name='referral_list_referral_map')
    op.drop_index(op.f('ix_referral_list_referral_map_map_referal'), table_name='referral_list_referral_map')
    op.drop_table('referral_list_referral_map')
    op.drop_index(op.f('ix_referral_list_member_map_map_reflist'), table_name='referral_list_member_map')
    op.drop_table('referral_list_member_map')
    op.drop_index(op.f('ix_referral_list_list_uuid'), table_name='referral_list')
    op.drop_table('referral_list')
    op.drop_index(op.f('ix_referral_ref_uuid'), table_name='referral')
    op.drop_table('referral')
    ### end Alembic commands ###
